config/routes.rb
Urodziny::Application.routes.draw do

  devise_for :users

  resources :users, only: :show do
    resources :birthdays, only: [:new, :create, :edit, :update, :destroy]
  end

  root :to => 'static_pages#welcome'

  mount Resque::Server, at: '/resque'

end

app/models/birthday.rb
class Birthday < ActiveRecord::Base
  attr_accessible :date, :name, :nick, :surname, :user_id

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :birthdays
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery   
          
  def after_sign_in_path_for(resource)
    sign_in_url = url_for(:action => 'new', :controller => 'sessions', :only_path => false, :protocol => 'http')
    if request.referer == sign_in_url
      current_user # super
    else
      root_path # stored_location_for(resource) || request.referer || root_path
    end
  end
end

app/controllers/birthdays_controller.rb
# coding: utf-8
class BirthdaysController < ApplicationController

  def new
    @birthday = current_user.birthdays.build
  end

  def create
    @birthday = current_user.birthdays.new(params[:birthday])
    if @birthday.save
      # TODO tu zapisać, kiedy trzeba wysłać przypomnienie listem
      UserMailer.birthday_reminder(current_user.id, @birthday.id).deliver
      redirect_to current_user, notice: 'Urodziny dodane :-)'
    else
      render 'new', alert: 'Popraw błędy.'
    end
  end

  def edit
    @birthday = current_user.birthdays.find(params[:id])
  end

  def update
    @birthday = current_user.birthdays.find(params[:id])
    if @birthday.update_attributes(params[:birthday])
      # TODO tu znaleźć zakolejkowane przypomnienie i zmienić je
      UserMailer.birthday_reminder(current_user.id, @birthday.id).deliver
      redirect_to current_user, notice: 'Urodziny zmienione :-)'
    else
      render 'edit', alert: 'Popraw błędy.'
    end
  end

  def destroy
    @birthday = current_user.birthdays.find(params[:id])
    # TODO tu znaleźć zakolejkowane przypomnienie i odwołać je
    @birthday.destroy
    render 'users/show'
    # redirect_to current_user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birthdays_helper.rb
module BirthdaysHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/birthdays/_fields.html.erb
<% if @birthday.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@birthday.errors.count, "error") %> prohibited this birthday from being saved:</h2>

    <ul>
    <% @birthday.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= f.label 'data' %>
<%= f.date_select :date, start_year: Date.today.year-110, end_year: Date.today.year %>

<%= f.label 'imię' %> 
<%= f.text_field :name %>

<%= f.label 'nazwisko' %>
<%= f.text_field :surname %>

<%= f.label 'pseudonim' %>
<%= f.text_field :nick %>


app/views/birthdays/edit.html.erb
<h1>zmień urodziny</h1>

<%= form_for(@birthday, url: user_birthday_path(current_user, @birthday)) do |f| %>
  <%= render 'fields', f: f %> <br/>  
  <%= f.submit 'zmień', class: "btn btn-large btn-primary" %>
<% end %>

<%= link_to 'Cofnij', current_user %>

app/views/birthdays/new.html.erb
<h1>dodaj urodziny</h1>

<%= form_for(@birthday, url: user_birthdays_path) do |f| %>
  <%= render 'fields', f: f %> <br/>  
  <%= f.submit 'dodaj', class: "btn btn-large btn-primary" %>
<% end %>

app/views/layouts/_nav.html.erb
<nav>
	<ul>
		<% if user_signed_in? %>
			<li><%= link_to current_user.email, user_path(current_user) %></li>
			<li><%= link_to 'wyjdź', destroy_user_session_path, method: :delete %></li>
			<li><%= link_to 'dodaj', new_user_birthday_path(current_user) %></li>
		<% end %>
	</ul>
</nav>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "urodziny" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">urodziny</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
							<% if user_signed_in? %>
								<li><%= link_to current_user.email, user_path(current_user) %></li>
								<li><%= link_to 'wyjdź', destroy_user_session_path, method: :delete %></li>
								<li><%= link_to 'dodaj', new_user_birthday_path(current_user) %></li>
							<% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
<!-- 
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div>
 -->
        <div class="span6 offset3">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; 4rko 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/static_pages/welcome.html.erb
<% if user_signed_in? %>
	<h1>Witaj <%= current_user.email %>!</h1>
	<p>:-]</p>
	<p>Możesz się <%= link_to 'wylogować', destroy_user_session_path, method: :delete %>.</p>
<% else %>
	<h1>Witaj!</h1>
	<p>Masz dużo znajomych, na których Ci zależy? Już nigdy nie zapomnisz o ich święcie!</p>
	<p>Możesz się <%= link_to 'zarejestrować', new_user_registration_path, class: 'btn btn-primary' %> 
		albo <%= link_to 'zalogować', new_user_session_path, class: 'btn btn-success' %>.</p>	
<% end %>

app/views/users/show.html.erb
<h1><input type='textfield' placeholder="czyje?" id="q"></input></h1>

<table class='table'>
<!--   <tr>
    <th>data</th>
    <th>imię</th>
    <th>nazwisko</th>
    <th>pseudonim</th>
    <th>zdjęcie</th>
  </tr> -->

	<% current_user.birthdays.each do |birthday| %>
	  <tr class="search_item">
	    <td><%= birthday.date %></td>
	    <td class="search_text"><%= birthday.name %></td>
	    <td class="search_text"><%= birthday.surname %></td>
	    <td class="search_text"><%= birthday.nick %></td>
      <td>
      	<%= link_to 'zmień', edit_user_birthday_path(current_user, birthday), class: 'btn btn-mini' %>
      	<%= link_to 'pozbądź się', user_birthday_path(current_user, birthday), method: :delete, class: 'btn btn-mini btn-danger' %> 
      </td>
	  </tr>
	<% end %>
</table>